config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :labels
  resources :notes 
  root "notes#index"  

  post 'update', to: 'notes#update'
  post 'create', to: 'notes#create'
  post 'notes/:id', to: 'notes#restore', as: 'restore'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/label.rb
class Label < ApplicationRecord
  has_and_belongs_to_many :notes
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user

  has_and_belongs_to_many :labels
  mount_uploader :image, ImageUploader

  enum deleted: {show:0 ,bin:1, deleted:2}

  def self.notes_empty
    Note.where(title: " ").where(description: " ").where(date: nil).where(time: nil)
  end

  def self.search(search)
    if search 
      Note.where("title ilike ?", "%#{search}%")
      # debugger

    end
    
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up){ |u| u.permit(:name, :email, :phone_number, :password, :password_confirmation)}
  end

end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  def index
    @labels = Label.all.order(:name)
    
  end

  def new
    @action = 'new'
    @label = Label.new()
  end

  def create
    @label = Label.new(label_params)
    debugger
    if @label.save!
      redirect_to labels_path
    else
      render 'new'
    end
  end

  def show
    @label = Label.find(params[:id])
  end

  def edit
    @action = 'edit'
    @label = Label.find(params[:id])
  end

  def update
    @label = Label.find(params[:id])
    if @label.update(label_params)
      redirect_to labels_path
    else
      render 'edit'
    end
  end

  def delete
  end



  private
  def label_params
    params.require(:label).permit(:name)
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
 before_action :authenticate_user!
 skip_before_action :verify_authenticity_token
  def index
    @notes = Note.all.order(:id) 

    # debugger
    @notes = Note.search(params[:title]) if params[:title]
    @empty_note = Note.notes_empty
    Note.find(@empty_note[0].id).destroy if @empty_note.present?
    # debugger

  end

  def new
    @action = 'new'
    @note = Note.new()
  end

  def create
    # debugger
    @note = current_user.notes.new(note_params)
    @note.save!
    respond_to do |format|
      format.json{render json: @note.id.to_json}
    end
  end

  def show
    @note = Note.find(params[:id])
  end

  def edit
    @action = 'edit'
    @note = Note.find(params[:id])
  end

  def update
    # debugger
    @note = current_user.notes.find(params[:note][:id])
    @note.update(note_params)
  end

  def destroy
    @note = Note.find(params[:id])
    if @note.deleted == 'show'
      @note.update(deleted: 1, deleted_time: Time.now)
    else      
      @note.update(deleted: 2)
    end
    redirect_to root_path
  end

  def restore
    # debugger
    @note = Note.find(params[:id])
    @note.update(deleted: 0, deleted_time: nil)
    redirect_to root_path
  end

  private

  def note_params
    params.require(:note).permit(:title, :description, :date, :time, :archive, :image, :pinned)
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/label_helper.rb
module LabelHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/labels/_label.html.erb
<div class="d-flex justify-content-center", id="">
  <div class="card" style="width: 18rem;">
    <%= form_with model: @label, url: @action == 'edit' ? label_path : labels_path, method: @action == 'edit' ? :patch : :post do |form| %>
      <%= form.label :name, 'Label', class:'form-control' %>
      <%= form.text_field :name, placeholder: '', class:'form-control' %>
      <%= form.submit 'save' %>
    <% end %>
  </div>
</div>

app/views/labels/create.html.erb
<h1>Label#create</h1>
<p>Find me in app/views/label/create.html.erb</p>

app/views/labels/delete.html.erb
<h1>Label#delete</h1>
<p>Find me in app/views/label/delete.html.erb</p>

app/views/labels/edit.html.erb
<%= render 'label' %>

app/views/labels/index.html.erb
<div id="main-div">

<%= link_to 'create label', new_label_path, method: :get %>
<%= link_to 'create a new note', new_note_path, class:'note' ,method: :get %>

  <div class="label">
    <% @labels.each do |label|%>
      <div class="card" style="width: 18rem;">
          <h5 class="card-title"><%= label.name %></h5>
          <%= button_to 'Edit', edit_label_path(label), method: :get%>
          <%= button_to 'Delete', label_path(label), method: :delete%>
      </div> 
    <% end %>
  </div>
</div>

app/views/labels/new.html.erb
<%= render 'label' %>

app/views/labels/update.html.erb
<h1>Label#update</h1>
<p>Find me in app/views/label/update.html.erb</p>

app/views/layouts/_header.html.erb
<div id="mySidebar" class="sidebar">
  <a href= "/#note-view", id="note" >Notes</a>
  <a href="/#reminder-view", id="reminder">Reminders</a>
  <a href="/#pinned-view", id="pinned">Pins</a>
  <a href="/#archive-view", id="archive">Archive</a>
  <a href="/#bin-view", id="bin">Bin</a>
</div>


<nav class="navbar navbar-light bg-light ">

  <a class=" navbar-brand openbtn" >☰ Keep</a>  
  <% if user_signed_in? %>
    <%= link_to "Sign out", destroy_user_session_path, class: 'navbar-brand float-end', method: :get %>

  <% else %>
  <div class="float-end ">
    <%= link_to "Sign up", new_user_registration_path, class: 'navbar-brand text-sm', method: :get %>
    <%= link_to "Sign in", new_user_session_path, class: 'navbar-brand text-sm' , method: :get %>
    
  </div>
  <% end %>


</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoogleKeepClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-3.1.1.min.js">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    <link href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css" rel="stylesheet">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "collapse_bar"%>
  </head>

  <body>
    <%= render "layouts/header"%>
    <%= yield %>
  </body>
</html>

<%= javascript_include_tag 'collapse_bar' %>

app/views/notes/_card.html.erb
<% @notes.each do |note|%>
   <div class="card" style="width: 18rem;">
      <img src="..." class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title"><%= note.title %></h5>
        <p class="card-text"><%= note.description %></p>
        <a href="#" class="btn btn-primary">Go somewhere</a>
      </div>
    </div>

<% end %>

app/views/notes/_notes.html.erb
<div class="d-flex justify-content-center", id="main-new">
  <div class="card" style="width: 20rem;">
    <%= form_with model: @note, url: @action == 'edit' ? note_path : notes_path, method: @action == 'edit' ? :patch : :post do |form| %>
      <%= form.label :pinned,'Pin' ,class:'click' %>
      <%= form.check_box :pinned,  class:'click pinned'%>


      <%= form.label :archive, 'Archive'%>
      <%= form.check_box :archive, class:'click archive'%>

      <%= form.text_field :title, placeholder: 'Title', class:'form-control click' %>
       <%= form.text_field :description, placeholder: 'Take a note...', class:'form-control  click' %>

      <div class="reminder-div" style="display: none;">
      <%= form.date_field :date, min: Time.now , class:'click'%>
      <%= form.time_field :time, value: "%H:%M", min: Time.now.strftime("%H:%M"), class:'click' %>
      </div>

      <input type="button", value="Add reminder", class="reminder-btn click">
      <%= form.text_field :id, value: @note.id, type:'hidden', id:'note_id' %>
    <% end %>
  </div>
</div>


<script >
  reminder = document.querySelector('.reminder-btn')
  reminder.addEventListener('click', function() {
    document.querySelector('.reminder-div').style.display = 'block'
    reminder.style.display = 'none'
  })

  pinned = document.querySelector(".pinned")
  pinned.setAttribute("value", "0")  
  pinned.addEventListener('click', function(){
    if (pinned.checked == true) {
      pinned.setAttribute("value", "1")
      console.log(pinned.value)
    }else {
      pinned.setAttribute("value", "0")
      console.log(pinned.value)
    } 

  })

  archive = document.querySelector(".archive")
  archive.setAttribute("value", "0")  
  archive.addEventListener('click', function(){
    if (archive.checked == true) {
      archive.setAttribute("value", "1")
      console.log(archive.value)
    }else {
      archive.setAttribute("value", "0")
      console.log(archive.value)
    } 

  })

</script>

<%= javascript_include_tag 'save' %>

app/views/notes/create.html.erb
<h1>Notes#create</h1>
<p>Find me in app/views/notes/create.html.erb</p>

app/views/notes/destroy.html.erb
<h1>Notes#destroy</h1>
<p>Find me in app/views/notes/destroy.html.erb</p>

app/views/notes/edit.html.erb
<%= render 'notes'%>

app/views/notes/index.html.erb
<% if user_signed_in? %>


<div id="main-div", class=""  >
  <%= link_to new_note_path, class:'underline' do %>
  <div class="card mx-auto p-3 mb-3" style="width: 18rem;">
    <p class="card-text">Take a note... </p>
  </div>
  <hr>
  <% end %>


  <div class="d-flex flex-wrap justify-content-evenly child">
    
    <% @notes.each do |note| %>
      <% if current_user.id == note.user_id %>
        <div id="note-view", style="display: block; ",  class="note-view selected" >
          <!-- notes -->
          <%= link_to note_path(note), class:'underline' do %>

            <% if note.pinned && (note.deleted == 'show') %>
              <div>
                <div class="card " style="width: 18rem; color: black;">
                  <%= image_tag note.image_url, style: 'height:100%;width:18rem'  if note.image_url.present? %>
                  <div class="card-body ">
                    <h5 class="card-title"><%= note.title %></h5>
                    <p class="card-text"><%= note.description %></p>  
                  </div>
                </div>

              </div> 
            <% end %>


            <% if (!note.pinned) && (!note.archive) && (note.deleted == 'show')%>
                <div class="card" style="width: 18rem; color: black;">
                  <%= image_tag note.image_url,style: 'height:100%;width:18rem' if note.image_url.present? %>
                  <div class="card-body ">
                    <h5 class="card-title"><%= note.title %></h5>
                    <p class="card-text"><%= note.description %></p>
                    <p class="card-text"><%= note.date if note.date.present? %></p>
                    <p class="card-text"><%= note.time  if note.time.present? %></p>
                  </div>
                </div>
            <% end %>
          <% end %>
        </div>

        <div id="reminder-view" , style="display: none;">
          <!-- reminder -->
          <%= link_to note_path(note), class:'underline' do %>
            <% if (note.date.present? || note.time.present?) && (note.deleted == 'show') %>
             <div class="card" style="width: 18rem;  color: black;">
              <%= image_tag note.image_url, style: 'height:100%;width:18rem' if note.image_url.present? %>
                <div class="card-body">
                  <h5 class="card-title"><%= note.title %></h5>
                  <p class="card-text"><%= note.description %></p>
                  <p class="card-text"><%= note.date if note.date.present? %></p>
                  <p class="card-text"><%= note.time.strftime("%H:%M") if note.time.present? %></p>    
                </div>
              </div>     
            <% end %>
          <% end %>
        </div>

        <div id="pinned-view" class="pinned-view selected", style="display: none;">
          <!-- pinned -->
          <%= link_to note_path(note), class:'underline' do %>

            <% if note.pinned && (note.deleted == 'show') %>
              <div>
                <div class="card" style="width: 18rem; color: black;">
                  <%= image_tag note.image_url, style: 'height:100%;width:18rem'  if note.image_url.present? %>
                  <div class="card-body ">
                    <h5 class="card-title"><%= note.title %></h5>
                    <p class="card-text"><%= note.description %></p>  
                  </div>
                </div>
              </div> 
            <% end %>
          <% end %>
        </div>


        <div id="archive-view" class="archive-view selected", style="display: none;">
          <!-- archive -->
          <%= link_to note_path(note), class:'underline' do %>
            <% if note.archive && (note.deleted == 'show') %>
             <div class="card" style="width: 18rem;  color: black;">
              <%= image_tag note.image_url, style: 'height:100%;width:18rem' if note.image_url.present? %>
                  <div class="card-body">
                  <h5 class="card-title"><%= note.title %></h5>
                  <p class="card-text"><%= note.description %></p>
                </div>
              </div>     
            <% end %>
          <% end %>
        </div>

        <div id="bin-view" class="bin-view selected", style="display: none;">
          <!-- bin -->
          <%= link_to note_path(note), class:'underline' do %>
            <% if note.deleted == 'bin'  %>
              <div class="card" style="width: 18rem;  color: black;">
                <%= image_tag note.image_url, style: 'height:100%;width:18rem' if note.image_url.present? %>
                <div class="card-body">
                  <h5 class="card-title"><%= note.title %></h5>
                  <p class="card-text"><%= note.description %></p>
                </div>
              </div>     
            <% end %>
          <% end %>
        </div>

      <% end %>
    <% end %>
  </div>
</div>

<% end %>

app/views/notes/new.html.erb
<%= render 'notes'%>

app/views/notes/show.html.erb
<div class="d-flex justify-content-center">
  <% if @note.deleted == 'show' %>
    <%= link_to edit_note_path(@note), class:'underline'  do %>
      <div class="card" style="width: 18rem;  color: black;">
        <%= button_to  note_path(@note), method: :delete, class:'delete-btn' do %>
          <i class="ri-delete-bin-fill"></i>        
        <% end %>
        <%= image_tag @note.image_url if @note.image_url.present? %>
        <div class="card-body">
          <h5 class="card-title"><%= @note.title %></h5>
          <p class="card-text"><%= @note.description %></p>  
          <p class="card-text"><%= @note.date if @note.date.present? %></p>
          <p class="card-text"><%= @note.time  if @note.time.present? %></p>
        </div>
      </div>
    <% end%>
  <% end %>

  <% if @note.deleted == 'bin' %>
      <div class="card" style="width: 18rem;  color: black;">
        <%= button_to  note_path(@note), method: :delete, class:'permanent-delete-btn' do %>
          <i class="ri-delete-bin-fill"></i>
        <% end %>
        <%= button_to  restore_path(@note), method: :post, class:'restore-btn' do %>
          <i class="ri-refresh-line"></i>
        <% end %>
        <%= image_tag @note.image_url if @note.image_url.present? %>
        <div class="card-body">
          <h5 class="card-title"><%= @note.title %></h5>
          <p class="card-text"><%= @note.description %></p>  
          <p class="card-text"><%= @note.date if @note.date.present? %></p>
          <p class="card-text"><%= @note.time  if @note.time.present? %></p>
        </div>
      </div>
  <% end %>

</div> 



<script>
  // deleteBtn = document.querySelector('.delete-btn')
  $('.delete-btn').click( function(){
    alert('Note added to bin')
  })
  $('.permanent-delete-btn').click( function(){
    alert('Note permanent deleted')
  })
  $('.restore-btn').click( function(){
    alert('Note is restored')
  })

</script>

app/views/notes/update.html.erb
<h1>Notes#update</h1>
<p>Find me in app/views/notes/update.html.erb</p>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>